### ISSUE TITLE
Logo Design For BYB

### ISSUE THREAD

**Issue by zularizal** [AkashG6/BYB#1]
Hi @AkashG6 ,  I'm a graphic designer, after I review your project, I'm interested in your project and I want to contribute by creating a logo/icon for your project. What do you think?

**Comment by AkashG6** [comment]
Feel free to contribute. A logo for the app would be really appreciated.

**Comment by zularizal** [comment]
Okay, I am designing it.

**Comment by zularizal** [comment]
Sorry for being late in reply. This is my design logo for your project. This logo is inspired by initial BYB and personality. What do you think?

If something wants to be changed please let me know.

![bitmap](https://user-images.githubusercontent.com/38547278/46122726-9baa6400-c244-11e8-9ec4-f1a03c0f648d.png)

**Comment by AkashG6** [comment]
Hey, thank you for your efforts. We loved the logo design. The project is on hiatus for now. In case of any concerns, we will update you through this issue once the development resumes.

**Comment by zularizal** [comment]
Okay..
